apiVersion: v1
kind: Service
metadata:
  name: postgres-apollo
  labels:
    external: gcp-cloud-sql
spec:
  ports:
    - port: 5432

---

apiVersion: v1
kind: Endpoints
metadata:
  name: postgres-apollo
  labels:
    external: gcp-cloud-sql
subsets:
  - addresses:
      - ip: 10.91.1.3
    ports:
      - port: 5432

---

apiVersion: v1
kind: Service
metadata:
  name: redis-apollo
  labels:
    external: gcp-memorystore
spec:
  ports:
    - port: 6379

---

apiVersion: v1
kind: Endpoints
metadata:
  name: redis-apollo
  labels:
    external: gcp-memorystore
subsets:
  - addresses:
      - ip: 10.55.69.107
    ports:
      - port: 6379
