apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  labels:
    app: celery
  name: celery
spec:
  replicas: 1
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  template:
    metadata:
      labels:
        app: celery
    spec:
      containers:
      - name: celery
        image: gcr.io/w11-apollo/backend:master-062f0b47
        imagePullPolicy: Always
        command: ["celery", "-A", "taskapp", "worker"]
        envFrom:
        - configMapRef:
            name: backend-env
        - secretRef:
            name: backend
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 50m
            memory: 200Mi
